---
# This meta data should be filled out.
title: Oral Qualifying Exam
description: Oral Qualifying Exam
keywords:
  - dichalcogenides
  - superconductivity
  - valley physics
  - valley hall effect
  - mos2
  - 2015
  - physics
  - deck.js
  - talk
locale: en_US
site_name: evansosenko.com
color: "#00695c"

# This meta data is optional.
# determiner: null
image: https://io.evansosenko.com/deck-ucr-exam/crystal.png
# audio: https://razor-x.github.io/jekyll-and-deck.js/talk.mp3
# video: https://razor-x.github.io/jekyll-and-deck.js/talk.mpg
# type: website
#
twitter:
  card: summary
  site: "@evansosenko"
  creator: "@evansosenko"
